import { Box, Container, Grid, Heading } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

export async function getServerSideProps() {
  const response = await fetch('http://localhost:4000')
  const data = await response.json()
  return {
    props: {
      data
    },
  }
}

const Home: NextPage = ({ data }) => {
  return (
    <Container maxWidth="container.lg">
      <Grid gap="4">
        <Head>
          <title>Essence</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Heading>Essence reader</Heading>
        {data.items.map(({ title, content }) =>
          <Box key={title} bg="gray.100" p="4">
            <Heading size="sm">{title}</Heading>
            <div dangerouslySetInnerHTML={{ __html: content}}></div>
          </Box>
        )}
      </Grid>
    </Container>
  )
}

export default Home
